### PR TITLE
add map for testing

### PR DESCRIPTION
**Pull request by thatdanguy23**
keep in mind that engineering doesnt exist right now, so if any testing needs to occur, periodically use secrets > power all APCs

### CODE REVIEW

**Comment by Spacemanspark** [comment]
What if the station explodes and we need engineers to fix it? Bad PR 0/10 un merge at once

**Comment by AffectedArc07** [comment]
Tip for future: Mapmerge

**Comment by thatdanguy23** [comment]
> Tip for future: Mapmerge

i forgot that was a thing, thank you papa arc

**Comment by Spacemanspark** [comment]
OH GOD ARC IS HERE QUICK HIDE THE SYNTHANOL

**Comment by AffectedArc07** [comment]
> OH GOD ARC IS HERE QUICK HIDE THE SYNTHANOL

I see everything

**Pull request merged**
